### ISSUE TITLE
Losing access to server after provisioning

### ISSUE THREAD

**Issue by NavyAnt24** [TalkingQuickly/rails-server-template#15]
Hey Ben, when I am setting up a new server, I copy my public ssh key `ssh-copy-id -i ~/.ssh/id_rsa.pub ubuntu@my-server.amazonaws.com` and am able to enter my server fine.

But after I download a new copy of this template (updating the nodes/my-server.json file to this:)

    {
        "environment": "production",
        "authorization": {
            "sudo": {
                "users": ["deploy", "vagrant"]
            }
        },
        "run_list": [
            "role[server]",
            "role[postgres-server]"
        ],
        "automatic": {
            "ipaddress": "my-server.amazonaws.com"
        },
        "postgresql": {
            "password": {
                "postgres": "password"
            }
        }
    }

And also updating the deploy.json user in `data_bags/users`:

    {
        "id": "deploy",
          // generate this with: openssl passwd -1 "plaintextpassword"
          "password": "password",
          "ssh_keys": [ "ssh-rsa my-public-key from ~/.ssh/id_rsa.pub"
          ],
          "groups": [ "sysadmin"],
          "shell": "\/bin\/bash"
    }

For some weird reason, after provisioning the server with `bundle exec knife solo bootstrap ubuntu@my-server.com`, I get a `Permission denied (publickey)` error. When trying to log-in using ssh, I get asked for the password for the `ubuntu` user, which I don't know. I can't even log in with my key pair `.pem` file from Amazon EC2 anymore.

Am I missing something? I didn't change the server.json role, and I can't seem to figure out what is going on. Has something changed my ssh configuration during provisioning?

**Comment by TalkingQuickly** [comment]
Closing this one for now but if you're still having problems let me know and happy to re-open
