### ISSUE TITLE
Postgres User password is not applied during provisioning

### ISSUE THREAD

**Issue by johnmcdowall** [TalkingQuickly/rails-server-template#16]
When the provisioning is complete, with the following configuration:

```
"postgresql": {
    "password": {
        "postgres": "<output from openssl passwd -1 password goes in here>"
    }
}
```

It should be expected that we can log on as the postgres user by doing:

```
$ su postgres
<entering password from the config above>
```

But in fact, authentication is denied. From the opscode postgresql README, it would seem to indicate that a random password is assigned during provisioning regardless of what is specified in the config. 

Confirm / deny? :)

**Comment by bertomartin** [comment]
This is very misleading! come on, this is something that should be clearly pointed out on the front page. I have the same issue.

**Comment by TalkingQuickly** [comment]
Agreed it's misleading, latest version of the sample code (v4.0) moves away from Chef Solo completely in favour of Chef Zero which resolves the issue
