### ISSUE TITLE
rbenv seems to not be installed

### ISSUE THREAD

**Issue by bertomartin** [TalkingQuickly/rails-server-template#25]
When I login as root and run 'which rbenv', nothing comes back, meaning rbenv isn't installed. Also, I don't see the .rbenv directory. Likewise, 'which ruby' returns nothing. I use the chef recipe from this template with minimal changes. The only thing I did was to remove the vagrant option from my node.json file. I really don't understand why this is a problem. Going through the recipes, I see where rbenv is being installed, and actually looking at the locations on the server, rbenv is installed there. But this is just not working as indicated above.

**Comment by bertomartin** [comment]
so, rbenv is installed here: /usr/local/rbenv/bin/rbenv. Just running that gives me this output: /usr/local/rbenv/libexec/rbenv---version: line 17: cd: /home/deploy/.rbenv: No such file or directory. I'm confused now. this is a system-wide install of rbenv. where should the .rbenv directory be?

**Comment by bertomartin** [comment]
According to the first answer here: http://stackoverflow.com/questions/16815750/should-rbenv-be-installed-system-wide-or-at-a-user-level, it looks like system-wide install for rbenv is discouraged. It's really confusing that rbenv is installed, yet everything says it's not.

**Comment by TalkingQuickly** [comment]
Apologies, for some reasons haven't been getting notifications on this repo. Could you post a copy of the node definition you provisioned with? I'll then try and re-produce and see what's going on.

**Comment by TalkingQuickly** [comment]
closing for now, if this is still a problem and you can provide a copy of the node definition than happy to re-open
