### ISSUE TITLE
Capistrano aborts during deploy:setup with a SSHKit::Runner::ExecuteError: 

### ISSUE THREAD

**Issue by jose8a** [TalkingQuickly/rails-server-template#29]
I am trying to launch one of my projects on Github onto a Digital Ocean droplet.  I am using the rails-server-template repo from the book.  I cloned the repo as mentioned in the book.  I then followed both of the Quickstart chapters 4 and 16 (provisioning with Chef/Berkshelf, and deploying with Capistrano).

The provision script ran just fine, although it seemed to hang on first try.  It had no problems going through to completion on the second try.  And after checking the Droplet IP address, the NGINX server message appeared as expected, so things seemed to be working fine there.

So, then I tried running the Capistrano 'deploy:setup_config' command and it blows up right after (or maybe during) the Unicorn setup procedures.  See the error message below (it is only the part just before and after the error message appears.

Any idea on what the problem might be?  I ran the 'deploy:setup_config' with a few extra debug and trace options, but I still have no idea what caused capistrano to abort.

---------------------------------------------------------------------------------------------------------------
== ERROR MESSAGE BELOW:
---------------------------------------------------------------------------------------------------------------

DEBUG [b9208e5b] Command: ( RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.1.2 /usr/bin/env chmod +x /home/deploy/apps/shared/config/unicorn_init.sh )
D, [2015-03-19T03:04:56.581563 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: queueing packet nr 77 type 90 len 44
D, [2015-03-19T03:04:56.581839 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: sent 120 bytes
D, [2015-03-19T03:04:56.600361 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: read 52 bytes
D, [2015-03-19T03:04:56.600635 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: received packet nr 91 type 91 len 28
I, [2015-03-19T03:04:56.600775 #10311]  INFO -- net.ssh.connection.session[3fcae950b3bc]: channel_open_confirmation: 10 0 0 32768
I, [2015-03-19T03:04:56.601065 #10311]  INFO -- net.ssh.connection.channel[3fcae98a9d84]: sending channel request "env"
D, [2015-03-19T03:04:56.601241 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: queueing packet nr 78 type 98 len 44
I, [2015-03-19T03:04:56.601552 #10311]  INFO -- net.ssh.connection.channel[3fcae98a9d84]: sending channel request "exec"
D, [2015-03-19T03:04:56.601712 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: queueing packet nr 79 type 98 len 156
D, [2015-03-19T03:04:56.601891 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: sent 248 bytes
D, [2015-03-19T03:04:56.619705 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: read 88 bytes
D, [2015-03-19T03:04:56.620077 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: received packet nr 92 type 93 len 28
I, [2015-03-19T03:04:56.620336 #10311]  INFO -- net.ssh.connection.session[3fcae950b3bc]: channel_window_adjust: 10 +2097152
D, [2015-03-19T03:04:56.620778 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: received packet nr 93 type 99 len 12
I, [2015-03-19T03:04:56.621003 #10311]  INFO -- net.ssh.connection.session[3fcae950b3bc]: channel_success: 10
D, [2015-03-19T03:04:56.623588 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: read 140 bytes
D, [2015-03-19T03:04:56.624133 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: received packet nr 94 type 98 len 44
I, [2015-03-19T03:04:56.624377 #10311]  INFO -- net.ssh.connection.session[3fcae950b3bc]: channel_request: 10 exit-status false
D, [2015-03-19T03:04:56.624593 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: received packet nr 95 type 96 len 12
I, [2015-03-19T03:04:56.624688 #10311]  INFO -- net.ssh.connection.session[3fcae950b3bc]: channel_eof: 10
D, [2015-03-19T03:04:56.624819 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: received packet nr 96 type 97 len 12
I, [2015-03-19T03:04:56.624890 #10311]  INFO -- net.ssh.connection.session[3fcae950b3bc]: channel_close: 10
D, [2015-03-19T03:04:56.625106 #10311] DEBUG -- tcpsocket[3fcae8adb5e0]: queueing packet nr 80 type 97 len 28
INFO [b9208e5b] Finished in 0.044 seconds with exit status 0 (successful).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@104.131.156.16: no implicit conversion of nil into String
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
TypeError: no implicit conversion of nil into String
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capistrano-cookbook-0.2.1/lib/capistrano/cookbook/helpers/substitute_strings.rb:9:in `gsub!'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capistrano-cookbook-0.2.1/lib/capistrano/cookbook/helpers/substitute_strings.rb:9:in `block in sub_strings'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capistrano-cookbook-0.2.1/lib/capistrano/cookbook/helpers/substitute_strings.rb:8:in `each'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capistrano-cookbook-0.2.1/lib/capistrano/cookbook/helpers/substitute_strings.rb:8:in `sub_strings'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capistrano-cookbook-0.2.1/lib/capistrano/cookbook/tasks/setup_config.cap:29:in `block (4 levels) in <top (required)>'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capistrano-cookbook-0.2.1/lib/capistrano/cookbook/tasks/setup_config.cap:28:in `each'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capistrano-cookbook-0.2.1/lib/capistrano/cookbook/tasks/setup_config.cap:28:in `block (3 levels) in <top (required)>'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/jose8a/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => deploy:setup_config

**Comment by jose8a** [comment]
Would love some help here in diagnosing this problem.  Is this forum now abandoned?

**Comment by TalkingQuickly** [comment]
Not abandoned at all but I completely missed this issue so apologies! It's failing when substituting in strings on a nil error so it looks like there's a value missing somewhere, could you post your full `Capfile`, `deploy.rb` and `production.rb` (probably as gists). Cheers, Ben

**Comment by jose8a** [comment]
Hi Ben,
Hoping you can infer where I went wrong from the files posted here (Capfile, deploy.rb, production.rb).  I tried to follow the book as well as I know how, but I realize that I probably have several gaps in knowledge that may have led me astray.  Here's hoping that you can help me move forward, or Heroku will have to be my deployment vehicle of choice from here until ... :)

Here's a link to a gist containing the contents of the three files you requested.  The IP address for my Digital Ocean droplet is masked out in the production.rb file, otherwise, all other info is as copied there.

https://gist.github.com/jose8a/7f5668708f4c5c5f84a7/a4902327ae4a98019189af30dfc396fe1cf2ce97

**Comment by TalkingQuickly** [comment]
It looks like in `production.rb` (https://gist.github.com/jose8a/7f5668708f4c5c5f84a7/a4902327ae4a98019189af30dfc396fe1cf2ce97#file-production-rb-L12) on line 12 you've got `full_path_name` but it should be `full_app_name` so it's crashing when it tries to upload files because it relies on `full_app_name` to infer the path.

There's a reference configuration here; https://github.com/TalkingQuickly/capistrano-3-rails-template which may be useful for comparison!

Cheers and hope that helps!

**Comment by jose8a** [comment]
Hey Ben,
I finally got around to this project and your find was my sticking point.  I very much appreciate your taking the time to find it. I'm having an app-specific library crashing the deploy now, but it's something I need to fix in the app, I think. Anyways, I can now look forward to more in-depth learning of these deployment tools in the book.  Thanks again!!
