### ISSUE TITLE
Error Executing Action 'remove'on resource 'users_manage[sysadmin]'

### ISSUE THREAD

**Issue by chadzilla2080** [TalkingQuickly/rails-server-template#36]
Hello,

I also have another problem that I need help with. Again, I've followed an out-of-the-box pdf doc, that I followed each instruction and or command. However, I'm getting an error that's not enabling me to completely provision the server. 

I read the trace error messages to interpret what's wrong, I need some assistance here to understand what's the real problem. 

At the very bottom it shows the json key/value pair that shows the "data_bag" set to "users", I'm wondering if that should be edited to match the original data_bag" information????

Error Message Trace Below::

#################################################################################

Recipe: users::sysadmins
  * users_manage[sysadmin] action remove[2015-09-11T02:12:12-04:00] ERROR: Failed to list data bag items in data bag: "users"

    
    ================================================================================
    Error executing action `remove` on resource 'users_manage[sysadmin]'
    ================================================================================
    
    FFI_Yajl::ParseError
    --------------------
    lexical error: invalid char in json text.
              gin as deploy   "ssh_keys": [AAAAB3NzaC1yc2EAAAADAQABAAABAQD
                         (right here) ------^
    
    Cookbook Trace:
    ---------------
    /home/deploy/chef-solo/cookbooks-2/chef-solo-search/libraries/search/overrides.rb:127:in `search_data_bag'
    /home/deploy/chef-solo/cookbooks-2/chef-solo-search/libraries/search/overrides.rb:53:in `search'
    /home/deploy/chef-solo/cookbooks-2/chef-solo-search/libraries/search.rb:87:in `search'
    /home/deploy/chef-solo/cookbooks-2/users/providers/manage.rb:43:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /home/deploy/chef-solo/cookbooks-2/users/recipes/sysadmins.rb
    
     23: users_manage "sysadmin" do
     24:   group_id 2300
     25:   action [ :remove, :create ]
     26: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/deploy/chef-solo/cookbooks-2/users/recipes/sysadmins.rb:23:in `from_file'
    
    users_manage("sysadmin") do
      action [:remove, :create]
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name :users
      recipe_name "sysadmins"
      group_id 2300
      data_bag "users"
      search_group "sysadmin"
    end
    

Running handlers:
[2015-09-11T02:12:12-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-09-11T02:12:12-04:00] ERROR: Exception handlers complete
[2015-09-11T02:12:12-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 1 resources updated in 60.986782218 seconds
[2015-09-11T02:12:12-04:00] ERROR: users_manage[sysadmin] (users::sysadmins line 23) had an error: FFI_Yajl::ParseError: lexical error: invalid char in json text.
          gin as deploy   "ssh_keys": [AAAAB3NzaC1yc2EAAAADAQABAAABAQD
                     (right here) ------^

[2015-09-11T02:12:12-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.

#################################################################################

**Comment by TalkingQuickly** [comment]
Hey, the SSH key needs to be surrounded in quotes, its regular JSON so the
exception is just saying it can't parse it. Cheers, Ben

**Comment by chadzilla2080** [comment]
Hey Ben, Thanks, still a noob.
