### ISSUE TITLE
Chapter 5.1 mistakes

### ISSUE THREAD

**Issue by Freika** [TalkingQuickly/rails-server-template#43]
1. pages 93-94 (I've opened the book in iBooks, OS X, it's just before "Updating the Node" section): code snippets on both pages contains line `source "redis-server.erb"`, but it should be `source "redis.conf.erb"`
2. page 103, last code snippet in "Accessing attributes from a recipe" section: line `uri          node['redis-server]['ppa']` have missed `'` symbol and should look like `uri          node['redis-server']['ppa']`

**Comment by TalkingQuickly** [comment]
(1) is fixed in v4.0.0 of the book, think (2) is as well but may need to chat to you about it to make sure I'm looking at the right bit
