### ISSUE TITLE
ascii art question

### ISSUE THREAD

**Issue by baraka2000** [TalkingQuickly/rails-server-template#48]
Hi,

Love your book, use it and refer to it often. Sorry to post an issue for what is really a question but I couldn't find your email. 

I've setup a staging and production server. For some reason my staging has production ascii art on login. Where do I fix this??

Best,
Kevin

**Comment by baraka2000** [comment]
I've looked everywhere... Any clue is appreciated.

**Comment by TalkingQuickly** [comment]
The text comes from this cookbook; https://github.com/TalkingQuickly/look_and_feel-tlq it looks to see whether the 'environment' attribute is set to `production` and if so, adds the banner. The new version of the book (4.0.0) due out later today, actually removes this cookbook completely from the default configuration but it will definitely remain available!
