### ISSUE TITLE
nginx erro please give me a hand.

### ISSUE THREAD

**Issue by TCnet** [TalkingQuickly/rails-server-template#55]
when i use  knife zero bootstrap ,it display the erro:
Fetching 'nginx' from git://github.com/miketheman/nginx.git (at master)
STDERR: Git error: command `git reset --hard e36944b0dac1f21044a4f0d01fc566023325cfde` failed.If this error persists, try removing the cache directory at '/Users/lujuhuang/.berkshelf/.cache/git/a7e1b73c3018df83378b1e5e78affe3e5399e301'.Output from the command:

fatal: Could not parse object 'e36944b0dac1f21044a4f0d01fc566023325cfde'.

**Comment by cstrutton** [comment]
I had to update the nginx line in Berksfile to target the 2.7 branch:
cookbook 'nginx', github: 'miketheman/nginx', branch: '2.7.x'

**Comment by TCnet** [comment]
Thanks, i had done the same thing.:)

**Comment by TalkingQuickly** [comment]
Thanks for this, fixed in the 5.0/ Ubuntu 20.04 release
