### ISSUE TITLE
Monit does not monitor memcached

### ISSUE THREAD

**Issue by shadysayed** [TalkingQuickly/rails-server-template#56]
It looks like monit does not monitor memcached on Ubuntu 16.04.

**Comment by shadysayed** [comment]
Could be related to this http://stackoverflow.com/questions/35077485/monit-memcached-config-without-pidfile

I looked at the memcached recipe and it looks like they use systemd after ubuntu 15.10 which seems to not use pid file

**Comment by shadysayed** [comment]
after some playing around it seems that the monit template needs to be overrided like
```bash
check process memcached with match memcached
   group memcache
   start program = "/usr/sbin/service memcached start"
   stop program = "/usr/sbin/service memcached stop"
   if failed host 127.0.0.1 port 11211 protocol memcache then restart
   if 3 restarts within 6 cycles then timeout
```

**Comment by CodeMonkeyG** [comment]
@shadysayed Thanks for figuring this out.

**Comment by TalkingQuickly** [comment]
Thanks for this, in the 5.0 (Ubuntu 20.04) release the monit configuration has been override to always write a pidfile so this should now be resolved.
