### ISSUE TITLE
Monit does not monitor postgresql

### ISSUE THREAD

**Issue by shadysayed** [TalkingQuickly/rails-server-template#57]
The default pidfile path for postgres is not the correct one. It needs to point to the correct pid file for the current postgres version ex: "/var/run/postgresql/9.5-main.pid"

**Comment by TalkingQuickly** [comment]
Thanks, you're entirely right, the latest version (5.0) which supports Ubuntu 20.04 has been upgraded to generate the pidfile location dynamically based on the selected Postgres version, so this shouldn't occur again
